# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevTutorial',
                'doc_host': 'https://Sean-RF.github.io',
                'git_url': 'https://github.com/Sean-RF/nbdevTutorial',
                'lib_path': 'nbdevTutorial'},
  'syms': {'nbdevTutorial.core': {'nbdevTutorial.core.foo': ('core.html#foo', 'nbdevTutorial/core.py')}}}
